### ISSUE TITLE
Handle url "pointers"

### ISSUE THREAD

**Issue by hadley** [r-pkgs/gh#27]
I make a call to a github api, and get a url: "https://api.github.com/repos/cloudera/gestalt/subscription". How can I use that url with gh?

**Comment by gaborcsardi** [comment]
I am not sure what you mean. Just take the url and call httr::GET on it?

What do you want to do with the url? Can you give an examle?

**Comment by gaborcsardi** [comment]
Oh, I see what you mean. GH often returns responses like these: https://developer.github.com/v3/activity/watching/#response

TBH I never understood this. If `/repos/:user/:repo/subscription` is part of the proper API, then why would I need to get the URL from the output of a `/repos/:owner/:repo` API call?

Is this because of how their Ruby client works?

**Comment by hadley** [comment]
What if gh provided `gh_GET()`, `gh_PUT()` etc that did less magic? If you gave them a full url, they're do the request against that; if you gave them a path they'd fill in the `.api_url`.

**Comment by gaborcsardi** [comment]
I think `gh` can just detect if it got a full URL or not. These can all work:

```r
gh("PUT /repos/...")
gh("PUT https://api.github.com....")
gh("PUT", "/repos/...")
gh("PUT", "https://api.github.com...")
```

**Comment by hadley** [comment]
How about at least an explicit method param?

**Comment by gaborcsardi** [comment]
That's the last two forms. Or I am not sure what you mean. You mean that 
```r
gh(url, method = "PUT")
```
should work, too? That's good, as long is there is no query parameter called `method`. My plan was to use all named arguments as query parameters, and the one or two unnamed ones are either just the URL, or the the method and the URL.

**Comment by hadley** [comment]
My feeling is that you're making the API too magical. Maybe that's ok for gh, but every time I've created something this magical in other packages, I've always come to regret it later on.

I'd argue that you want two interfaces:

* An exploratory interface that lets you copy and paste directly from github api examples 
* A programmable interface that has explicit arguments and no magic, and makes it easier to use gh from other functions

**Comment by gaborcsardi** [comment]
I don't think the current API is magical. It might be strange to get used to, but I think it is pretty minimal. You can indeed copy and paste from the api examples, add some query parameters, and that's it.

As for programmable, you are probably right, and it could have another function, something like

```r
gh2 <- function(path, method = "GET", query = list(), token = ..., headers = ...)
```

(No, I don't want to name it `gh2`, just could not find a good name yet.)
