### ISSUE TITLE
Couldn't connect to server 

### ISSUE THREAD

**Issue by hms15** [r-pkgs/gh#47]
When running devtools::install_github("gaborcsardi/gh") I get the following error:
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Couldn't connect to server

**Comment by gaborcsardi** [comment]
Strange. It works fine for me, can you please try again in a fresh R session, and if it does not work show the output of `devtools::session_info()`?

**Comment by hms15** [comment]
Got the same error. Below is my session info:

devtools::session_info()
Session info ----------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       RStudio (0.99.903)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         
 date     2016-11-23                  

Packages --------------------------------------------------------------------------------------
 package  * version date       source        
 curl       2.2     2016-10-21 CRAN (R 3.3.1)
 devtools   1.12.0  2016-06-24 CRAN (R 3.3.2)
 digest     0.6.10  2016-08-02 CRAN (R 3.3.1)
 git2r      0.15.0  2016-05-11 CRAN (R 3.3.2)
 httr       1.2.1   2016-07-03 CRAN (R 3.3.2)
 memoise    1.0.0   2016-01-29 CRAN (R 3.3.2)
 R6         2.1.3   2016-08-19 CRAN (R 3.3.1)
 withr      1.0.2   2016-06-20 CRAN (R 3.3.2)
>

**Comment by gaborcsardi** [comment]
Maybe it is a `devtools` issue? Here is an alternative way to install. The package has moved to the `r-pkgs` organization, btw, the README needs to be updated:

```r
source("https://install-github.me/r-pkgs/gh")
```

**Comment by hms15** [comment]
I tried the alternative method and got an error again:
> source("https://install-github.me/r-pkgs/gh")
Downloading GitHub repo r-pkgs/gh@master
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot download all files
Called from: utils::download.file(url, path, method = download_method(), quiet = quiet, 
    mode = "wb")
Browse[1]>

**Comment by gaborcsardi** [comment]
Is it possible that your local network or firewall does not allow this connection? Can you install other packages from GitHub? E.g. does the following work?

```r
source("https://install-github.me/gaborcsardi/httrmock"")
```

(This package is needed for `gh`, anyway....)

**Comment by hms15** [comment]
good point didn't even think of the firewall...let me try that...thanks

**Comment by hms15** [comment]
Thank you for your help :) - firewall was the issue. I was able to install the package!

**Comment by gaborcsardi** [comment]
No worries. :)
