### ISSUE TITLE
Testing token management

### ISSUE THREAD

**Issue by jennybc** [r-pkgs/gh#53]
The gh package prefers the token in `GITHUB_PAT` over that in `GITHUB_TOKEN`:

``` r
gh_token <- function() {
  token <- Sys.getenv('GITHUB_PAT', "")
  if (token == "") Sys.getenv("GITHUB_TOKEN", "") else token
}
```

But the testing setup enacts the testing account's token via `GITHUB_TOKEN` (only):

``` r
if (file.exists("github-token.txt")) {
  Sys.setenv(GITHUB_TOKEN = readLines("github-token.txt", n = 1))
  ...
}
```

If a developer has no `GITHUB_PAT`, then when the tests run, the testing token is used and all is well. I suspect this is true for @gaborcsardi.

But I have `GITHUB_PAT` defined with my personal PAT, so to ensure the testing token is used I need to  call `gh()` like so:

``` r
gh(..., .token = Sys.getenv("GITHUB_TOKEN"))
```

It seems like we should do one of these things and I think the second is a better idea:

  1. In `helper.R`, set both `GITHUB_TOKEN` and `GITHUB_PAT` to the testing token.
  1. Agree to specify the testing token explicitly in `gh()` calls in the tests.

What if we agree to store the testing token in its own env var? Then we can all define it in our usual way (e.g. in `.Renviron`). We can have a helper that retrieves it. Existence of this env var becomes the condition in `helper.R` instead of the existence of `github-token.txt`. And all `gh()` calls in tests use the helper to explicitly use the testing token.

I think this might be a nicer development workflow.

`helper.R` would look more like this:

``` r
tt <- function() Sys.getenv("GH_TESTING_TOKEN", NA)

...

if (!is.na(Sys.getenv("GH_TESTING_TOKEN")) {
  ## the mocking stuff still goes here
}
```

And a `gh()` call in the typical test looks like so:

``` r
gh(..., .token = tt())
```

Side benefit: if you ever wanted to make HTTP calls from travis or appveyor, now you just need to encrypt an env var vs a file.

If you approve @gaborcsardi, I will make the PR.

**Comment by gaborcsardi** [comment]
Thanks! Yes, I like this!

Why do you think 2. is better than 1., btw?

I mean, we can have `GH_TESTING_TOKEN`, and then set both `GITHUB_PAT` and `GITHUB_TOKEN` to it in `helper.R`. Why is an explicitly supplied token better?

**Comment by gaborcsardi** [comment]
If we generate the test cases, which we probably will, at least many of them, then it makes little difference if we do 1. or 2., I guess.

**Comment by jennybc** [comment]
> Why do you think 2. is better than 1., btw?

Because if I want to make a quick httr or gh call as "jennybc", this way my normal PAT is still the default. If we override `GITHUB_PAT` and `GITHUB_TOKEN`, then the current token is another thing I need to explicitly manage when developing.

**Comment by gaborcsardi** [comment]
> Because if I want to make a quick httr, devtools, or gh call as "jennybc", this way my normal PAT is still the default. 

This makes sense, but maybe I would solve this problem in general in `httrmock` instead of abusing the two tokens. E.g. `httrmock` could set up options and environment variables that are specific for the mocked contexts. Anyway, sg. to think about later.

**Comment by jennybc** [comment]
> Anyway, sg. to think about later.

Does that mean "no" on the PR? Or could you tolerate that solution temporarily? Because it somewhat eases my life today.

I think having an httrmock config file for gh would be super helpful. But the token itself can never be directly stored there because presumably the config file would be under version control?

**Comment by gaborcsardi** [comment]
No, sorry, I just went to sleep, and had to work 9-5. I'll merge it soon. :)

Yes, the token must be separate, but we need to put an encrypted version there.

**Comment by jennybc** [comment]
Are you in the UK? Because it still seems like you're keeping crazy hours, if so!

**Comment by gaborcsardi** [comment]
I merged the PR, and I'll close this now. I'll open another issue once I'll have some plan for better token management. And if we need it.
